apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: integration
  name: integration
  namespace: openshift-gitops
spec:
  destination:
    namespace: integration
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/int
    repoURL: https://github.com/mthirion/gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
