apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: development
  name: development
  namespace: openshift-gitops
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/gitops/dev
    repoURL: https://github.com/mthirion/gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
