apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: myquarkus
  name: dev-myquarkus
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/dev/myquarkus
    repoURL: https://github.com/mthirion/kam.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
